kind: Service
apiVersion: v1
metadata:
  name: mc-utils-influx-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.50.137
  ports:
    - name: http
      port: 8086
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mc-utils-influx-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`influx.mcutils.xyz`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: mc-utils-influx-external
          port: 8086
  tls:
    secretName: mcutils-xyz
