apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capacitor-external-ingress
  namespace: public-services
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`img.fascinated.cc`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: flyimg-service
          port: 80
  tls:
    secretName: fascinated-cc
