---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.crds.yaml
  - cert-manager.yaml
  - issuer.yaml
  - ./certificates/fascinated-cc.yaml
  - ./certificates/local-fascinated-cc.yaml
  - ./certificates/mcutils-xyz.yaml
