---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - cert-manager.yaml
  - issuer.yaml
  - ./certificates/fascinated-cc.yaml
  - ./certificates/local-fascinated-cc.yaml
  - ./certificates/mcutils-xyz.yaml
  - ./external-services
