---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: public-services
resources:
  - ./redis/pvc.yaml
  - ./redis/redis.yaml
  - config.yaml
  - sealed-secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
