kind: Service
apiVersion: v1
metadata:
  name: docs-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.50.254
  ports:
    - name: http
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docs-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`docs.fascinated.cc`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: docs-external
          port: 80
  tls:
    secretName: fascinated-cc
