kind: Service
apiVersion: v1
metadata:
  name: repo-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.50.164
  ports:
    - name: http
      port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: repo-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`repo.fascinated.cc`)
      kind: Rule
      services:
        - name: repo-external
          port: 8080
  tls:
    secretName: fascinated-cc
