kind: Service
apiVersion: v1
metadata:
  name: teleport-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.50.182
  ports:
    - name: https
      port: 3080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teleport-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`teleport.fascinated.cc`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: teleport-external
          port: 3080
  tls:
    secretName: fascinated-cc
