kind: Service
apiVersion: v1
metadata:
  name: wiki-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.50.254
  ports:
    - name: http
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wiki-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wiki.fascinated.cc`)
      kind: Rule
      services:
        - name: wiki-external
          port: 80
  tls:
    secretName: fascinated-cc
