apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  namespace: drone-ci
  labels:
    app.kubernetes.io/name: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone
    spec:
      containers:
        - name: runner
          image: drone/drone-runner-kube:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 75Mi
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: DRONE_RPC_HOST
              value: drone.local.fascinated.cc
            - name: DRONE_RPC_PROTO
              value: http
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_RPC_SECRET
